### ISSUE TITLE
ユーザーネームの編集機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#100]
### ■Summary

マイページでユーザーのユーザーネームを編集できるようにする機能を実装します。この変更は、右上の完了ボタンをクリックするまでサーバーに送信されません

### ■Path

`app/views/mypage/_edit_user.html.erb`

`app/controllers/users_controller.rb`

`app/assets/javascripts/mypage.js`

### ■Tasks

1. フロントエンドの実装
- [ ]  `app/assets/javascripts/mypage.js`ファイルを作成し、次の機能を追加
    - [ ]  完了ボタンをクリックしたときにフォームを送信する処理を追加
    - [ ]  ユーザーネームの変更内容をhiddenフィールドに保存する処理を追加
2. コントローラーの実装
- [ ]  `app/controllers/users_controller.rb`に次のアクションを追加・修正
    - [ ]  `edit`アクション：ユーザー編集フォームの表示
    - [ ]  `update`アクション：ユーザーネームの更新（hiddenフィールドからのデータ受け取り、更新処理）

### ■Goals

- ユーザーがマイページでユーザーネームを編集できるようにする
- 変更内容は、右上の完了ボタンをクリックするまでサーバーに送信されない
- 更新成功時および失敗時のフラッシュメッセージが適切に表示される
