### ISSUE TITLE
マイページ編集の完了ボタンによる一括更新機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#101]
### ■Summary

マイページ編集画面で、ユーザーおよびプレイヤーの情報（ユーザーネーム、プロフィール画像、プレイヤーの名前、誕生日、性別、プロフィール画像など）を一括で更新する機能を実装します

変更内容は、右上の完了ボタンをクリックするまでサーバーに送信されません

### ■Path

`app/views/mypage/edit.html.erb`

`app/controllers/users_controller.rb`

`app/controllers/players_controller.rb`

`app/assets/javascripts/mypage.js`

### ■Tasks

1. フロントエンドの実装
- [ ]  `app/views/mypage/edit.html.erb`に完了ボタンを追加し、各フォームを包含するメインフォームを作成
- [ ]  `app/assets/javascripts/mypage.js`に次の機能を追加
    - [ ]  完了ボタンをクリックしたときにフォームを送信する処理を実装
    - [ ]  各変更内容をhiddenフィールドに保存し、送信時に適切に処理されるようにする
    - [ ]  プレイヤー削除ボタンをクリックしたときに削除情報をhiddenフィールドに保存し、完了ボタンをクリックするまで削除を保留する処理を追加
2. コントローラーの実装
- [ ]  `app/controllers/users_controller.rb`の`update`アクションを修正し、ユーザー情報および関連するプレイヤー情報を一括で更新
- [ ]  `app/controllers/players_controller.rb`で、必要なプレイヤー情報の処理を追加

### ■Goals

- マイページ編集画面で、ユーザーおよびプレイヤーの情報を一括で更新できる
- 各変更は、右上の完了ボタンをクリックするまでサーバーに送信されない
- 更新成功時および失敗時のフラッシュメッセージが適切に表示される
