### ISSUE TITLE
ランキングデータの計算処理（controllerとroutes）

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#116]
### ■Summary

ランキングデータを計算する処理を実装します

### ■Path

`app/controllers/rankings_controller.rb`

`config/routes.rb`

### ■Tasks

- [ ]  RankingsControllerを生成
    - [ ]  indexアクションの追加
        - [ ]  `@players = Player.with_correct_and_incorrect_counts`
    - [ ]  ランキングデータをビューに渡す処理を追加
- [ ]  `rankings#index`アクションへのルートを追加
    - [ ]  `get 'rankings', to: 'rankings#index’`

### ■Goals

正確なランキングデータが計算され、順位を取得できること
