### ISSUE TITLE
回答記録のアソシエーションの設定

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#118]
### ■Summary

回答記録を管理するためにResultモデルとの関連付けを行います

### ■Path

`app/models/result.rb`

### ■Tasks

- [ ]  Resultモデルの関連付け
    - [ ]  `belongs_to :player`
    - [ ]  `belongs_to :question`
    - [ ]  `belongs_to :choice`
- [ ]  Playerモデルの関連付け
    - [ ] `has_many :results`
- [ ]  Questionモデルの関連付け
    - [ ] `has_many :results`
- [ ]  Choiceモデルの関連付け
    - [ ] `has_many :results`
- [ ]  マイグレーションを実行する

### ■Goals

関連付けにより、回答結果の履歴を管理できるようになり、playerとquestionとchoiceのどれかが削除されるとresultも削除されるようになる
