### ISSUE TITLE
回答結果後に表示されるページの作成（view）

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#121]
### ■Summary

ユーザーが回答を選択したときに正解か不正解かをチェックし、対応するアニメーションと音声を再生する機能を実装する

### ■Path

`app/views/results/correct.html.erb`

`app/views/results/incorrect.html.erb`

`app/views/results/streak.html.erb`

### ■Tasks

- [ ]  `app/views/results/correct.html.erb`の作成
    - [ ]  次の問題に進むリンクを配置
- [ ]  `app/views/results/incorrect.html.erb`の作成
    - [ ]  再チャレンジリンクを配置
- [ ]  `app/views/results/streak.html.erb`の作成
    - [ ]  10問連続正解を知らせる画像を表示
    - [ ]  動画再生ページへのリンクを配置

### ■Goals

- 正解時、正解用のページが表示され、次の問題に進むリンクが表示される
- 不正解時、不正解用のページが表示され、再チャレンジリンクが表示される
- 10問連続正解時、10問連続正解用のページが表示された後、動画ページへ遷移する
