### ISSUE TITLE
ログイン時の認証ロジックの実装(controller)

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#34]
### ■Summary

ログイン時、ユーザーのemailとpasswordを照合する認証ロジックを実装します

### ■Path

`app/controllers/sessions_controller.rb`

### ■Tasks

- [ ]  SessionsControllerを作成
- [ ]  newアクションを定義
- [ ]  createアクションを定義
    - [ ]  認証成功した時：ポップアップを表示し、トップページ、プレイヤー切り替えページ、問題ページへのリンクを選択すると対象ページに遷移
    - [ ]  認証失敗した時：ログインページにrenderされ、フラッシュメッセージで「ログインに失敗しました」を表示
- [ ]  Sorceryの`login`メソッドを使用してユーザーを認証

### ■Goals

createアクションが正しく機能し、ユーザーの認証が成功または失敗した場合の処理が実行されること
