### ISSUE TITLE
マイページとその編集画面のフォーム作成（view)

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#53]
### ■Summary

ユーザーが自身の情報を編集したり、新しいプレイヤーを作成、既存のプレイヤーを編集・削除できるマイページの編集画面フォームを作成する。

### ■Path

`app/views/mypage/edit.html.erb`

### ■Tasks

- [ ]  `app/views/mypage/show.html.erb`を作成する（マイページ表示用）
- [ ]  `app/views/mypage/edit.html.erb`を作成する（マイページ編集用）
- [ ]  各フォームを部分テンプレートとして作成し、マイページでまとめて表示する
    - [ ]  `_edit_user.html.erb`
    - [ ]  `_new_player.html.erb`
    - [ ]  `_edit_player.html.erb`
- [ ]  `app/views/mypage/edit.html.erb`で各部分テンプレートを`render`する

### ■Goals

マイページが表示され、マイページ編集画面には次のフォームが表示される

- [ ]  ユーザーが自身のユーザーネームとプロフィール画像を編集するフォーム
- [ ]  ユーザーが新しいプレイヤーを作成するフォーム
- [ ]  ユーザーが既存のプレイヤーを編集するフォーム
- [ ]  ユーザーが既存のプレイヤーを削除するフォーム
