### ISSUE TITLE
ユーザー編集機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#55]
### ■Summary

マイページでユーザーが自身のユーザーネームとプロフィール画像を編集できる機能を実装します

### ■Path

`app/controllers/users_controller.rb`

### ■Tasks

- [ ]  フォームのラベル
    - [ ]  username：名前
    - [ ]  profile_image：プロフィール画像のアップロード（file_fieldを使用）
- [ ]  `app/controllers/users_controller.rb`にeditとupdateアクションを定義
- [ ]  updateアクションでユーザー情報を更新
- [ ]  更新成功時にフラッシュメッセージ「ユーザー情報が更新されました」を表示し、マイページにリダイレクト
- [ ]  更新失敗時に編集ページを再表示し、フラッシュメッセージ「ユーザー情報の更新に失敗しました」を表示

### ■Goals

フォームから値を入力し、ユーザーの名前とプロフィール画像が編集されること
