### ISSUE TITLE
プレイヤー作成機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#56]
### ■Summary
ユーザーがマイページで新しいプレイヤーを作成できるコントローラを作成します
### ■Path
- [ ]  `app/controllers/players_controller.rb`
### ■Tasks
- [ ]  `app/controllers/players_controller.rb` を作成する
    - [ ]  newとcreateアクションを定義
    - [ ]  作成成功時にフラッシュメッセージ「プレイヤーが作成されました」を表示し、マイページにリダイレクト
    - [ ]  作成失敗時にマイページを再表示し、フラッシュメッセージ「プレイヤーの作成に失敗しました」を表示
- [ ]  `before_action`を使用して、`@user`を設定し、プレイヤーの作成と関連付ける
### ■Goals
createアクションが正しく機能し、プレイヤー登録が成功または失敗した場合の処理が実行されること

### ■Summary
プレイヤー登録機能を実装する際、データの正確性や一貫性を保つため、バリデーションを追加します
### ■path
`app/models/player.rb`
### ■Tasks
- [ ]  Userモデルに以下のバリデーションを追加
    - [ ]  name：必須
### ■Goals
フォームから値を入力して、バリデーションの条件を満たしていない場合、プレイヤー情報がデータベースに登録されないこと
