### ISSUE TITLE
プレイヤーのスコア表示機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#59]
### ■Summary
Resultモデルを作成し、プレイヤーごとの問題の解答内容を保存する

### ■Path
`app/models/result.rb`

### ■Tasks
- [ ]  Resultモデルの作成
    - [ ]  player_id、question_id、choice_id、timestamp、is_correctのフィールドを追加
- [ ]  マイグレーションファイルの作成とデータベースのマイグレーションを実行
- [ ]  モデル間のアソシエーションを設定（PlayerモデルとQuestionモデル）
    - [ ]  PlayerモデルとResultモデル：`has_many :results`
    - [ ]  ResultモデルとPlayerモデル：`belongs_to :player`
    - [ ]  QuestionモデルとResultモデル：`has_many :results`
    - [ ]  ResultモデルとQuestionモデル：`belongs_to :question`
    - [ ]  ChoiceモデルとResultモデル：`has_many :results`
    - [ ]  ResultモデルとChoiceモデル：`belongs_to :choice`

### ■Goals
プレイヤーごとの回答履歴をデータベースに保存できるようにする

### ■Summary
プレイヤーごとのスコアを計算し、ビューに渡す

### ■Path
`app/controllers/users_controller.rb`

### ■Tasks
- [ ]  Playersコントローラーにスコア計算用のメソッドを追加
- [ ]  各プレイヤーの正解数と不正解数を集計するロジックを実装
- [ ]  ビューにスコア情報を渡すためのインスタンス変数を設定
- calculate_scoreメソッド

### ■Goals
プレイヤーごとのスコアを正確に計算し、ビューで表示できるようにする

### ■Summary
プレイヤーの得点表示用HTMLを記述したパーシャルファイルを作成する

### ■Path
`app/views/mypage/_show_result.html.erb`

### ■Tasks
- [ ]  `_show_result.html.erb`パーシャルファイルを作成
- [ ]  プレイヤーの得点を表示するためのHTMLテンプレートを記述
- [ ]  正解数、不正解数を視覚的にわかりやすく表示するデザインを実装

### ■Goals
プレイヤーの得点を表示するパーシャルを提供し、簡単に他のビューに組み込めるようにする

### ■Summary
マイページにプレイヤーごとのスコアを表示する

### ■Path
`app/views/mypage/show.html.erb`

### ■Tasks
- [ ]  `mypage/show.html.erb`で`render 'mypage/show_result'`を使用してパーシャルを表示
- [ ]  マイページにスコア表示部分を追加

### ■Goals
マイページにプレイヤーの得点を表示し、ユーザーが容易に確認できるようにする
