### ISSUE TITLE
ユーザーフォームの作成（view）

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#6]
### ■Summary

ユーザー登録機能を実装するため、ユーザーデータを登録するためのページ(view)およびフォームを作成します

### ■path

`app/views/users/new.html.erb`

### ■Tasks

- [ ]  `app/views/users/new.html.erb`を作成
    - [ ]  form_withヘルパーを使用して、フォームを作成
    - [ ]  フォームに以下のラベルと入力フィールドを追加
        - [ ]  username：名前
        - [ ]  email：メールアドレス
        - [ ]  password：パスワード
        - [ ]  password_confirmation：パスワード確認
        - [ ]  登録ボタン

プロフィール画像のアップロードは新規登録時には行わず、マイページでのみ実施します。そのため、登録フォームにはプロフィール画像のフィールドは不要です。

**確認事項**

- [ ]  値を入力して`app/controllers/users_controller.rb`の`create`アクションにデータが送信され、データベースに保存される

### Goals

フォームから値を入力して、ユーザー情報がデータベースに登録されること
