### ISSUE TITLE
回答結果のバリデーション

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#68]
### ■Summary

回答結果を保存する際のバリデーションを追加します

### ■Path

`app/models/result.rb`

### ■Tasks

- [ ]  バリデーションの追加
    - [ ]  player_id：必須
    - [ ]  question_id：必須
    - [ ]  choice_id：必須
    - [ ]  is_correct：どちらか必須
        - [ ]  true
        - [ ]  false

### ■Goals

不正なデータが保存されないこと
