### ISSUE TITLE
バリデーション

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#7]
### ■Summary

ユーザー登録機能を実装する際、データの正確性や一貫性を保つため、バリデーションをつけます

### ■path

`app/models/user.rb`

### ■Tasks

- [ ]  Userモデルに以下のバリデーションを追加
    - [ ]  username：必須
    - [ ]  email：必須、ユニーク
    - [ ]  password：必須、8文字以上
    - [ ]  password_confirmation：必須、8文字以上、passwordの入力値と一致している

### ■Goals

フォームから値を入力して、バリデーションの条件を満たしていない場合、ユーザー情報がデータベースに登録されないこと
