### ISSUE TITLE
QuestionモデルとChoiceモデルのバリデーション

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#72]
### ■Summary

QuestionモデルとChoiceモデルにバリデーションを追加して、データの整合性を保つ

### ■Path

`app/models/question.rb`

`app/models/choice.rb`

### ■Tasks

- [ ]  Questionモデル
    - [ ]  `:content, presence: true`を追加
    - [ ]  `:image, presence: true`を追加
- [ ]  Choiceモデル
    - [ ]  `:content, presence: true`を追加
    - [ ]  `:is_correct, inclusion: { in: [true, false] }`を追加

### ■Goals

QuestionモデルとChoiceモデルにおいて、データの一貫性と正確性を確保し、無効なデータが保存されないようにする
