### ISSUE TITLE
admin_controller

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#73]
### ■Summary
管理者が新しい問題を作成できるようにするための機能を実装します
### ■Path
`app/controllers/admin/questions_controller.rb`
### ■Tasks
- [ ]  `app/controllers/admin/questions_controller.rb`を作成
    - [ ]  newとcreateアクションを定義
- [ ]  `routes.rb`に管理者用の質問作成ルートを追加
### ■Goals
管理者が新しい質問を作成できること

### ■Summary
管理者が既存の問題を編集できるようにするための機能を実装します
### ■Path
`app/controllers/admin/questions_controller.rb`
### ■Tasks
- [ ]  editとupdateアクションを追加
- [ ]  `app/views/admin/questions/edit.html.erb`を作成し
    - [ ]  問題の編集フォームを追加
    - [ ]  フォームには現在のcontentとimageのフィールドを表示
- [ ]  `routes.rb`にeditとupdateアクションのルートを追加
### ■Goals
管理者が既存の問題を編集できること

### ■Summary
管理者が既存の問題を削除できるようにするための機能を実装します
### ■Path
`app/controllers/admin/questions_controller.rb`
### ■Tasks
- [ ]  destroyアクションを追加
- [ ]  `routes.rb`にdestroyアクションのルートを追加
- [ ]  `app/views/admin/questions/index.html.erb`に削除ボタンを追加し、問題の一覧を表示
### ■Goals
管理者が既存の問題を削除できること
