### ISSUE TITLE
controller（問題の表示）

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#75]
### ■Summary

働く車の画像、質問、回答の選択肢を表示するビューを作成します

### ■Path

`app/views/questions/show.html.erb`

### ■Tasks

`app/views/questions/show.html.erb`の作成

- [ ]  問題文、画像、選択肢を表示するテンプレートを作成
- [ ]  問題文、画像、選択肢を表示するテンプレートを作成
    - [ ]  問題文を表示するための`<p>`タグを追加
    - [ ]  画像を表示するための`<img>`タグを追加
    - [ ]  選択肢を表示するための`<ul>`タグと`<li>`タグを追加
    - [ ]  各選択肢を選択するためのフォームを作成
    - [ ]  フォーム送信ボタンを追加

### ■Goals

ユーザーが問題と回答の選択肢を確認できること
