### ISSUE TITLE
認証成功時にJavaScriptを使ってポップアップを表示する機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#88]
### ■Summary

認証が成功した際に、JavaScriptを使用してユーザーにポップアップメッセージを表示する機能を追加します。このポップアップメッセージにより、ユーザーはログインが成功したことを視覚的に確認できます

### ■Path

`app/controllers/sessions_controller.rb`

`app/views/sessions/new.html.erb`

`app/assets/javascripts/sessions.js`

### ■Tasks

- [ ]  `app/controllers/sessions_controller.rb`の`create`アクションで、認証が成功した際にフラッシュメッセージを設定します。
- [ ]  `app/assets/javascripts/sessions.js`を作成し、ポップアップを表示するJavaScriptコードを実装
    - [ ]  フラッシュメッセージを取得
    - [ ]  取得したフラッシュメッセージをポップアップとして表示
    - [ ]  ポップアップのデザインを調整
    - [ ]  ポップアップが自動的に閉じるように設定
- [ ]  `app/views/layouts/application.html.erb`にJavaScriptファイルを読み込むコードを追加します
- [ ]  `app/views/layouts/application.html.erb`にフラッシュメッセージを表示するための領域を追加します

### ■Goals

ログインが成功した際に、ポップアップメッセージが表示され、ユーザーにログイン成功が視覚的に通知されること。
