### ISSUE TITLE
ポップアップにリンクを追加

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#89]
### ■Summary

ログイン成功時に表示されるポップアップメッセージに、トップページ、プレイヤー切り替えページ、および問題ページへのリンクを追加します。これにより、ユーザーはログイン後にスムーズに次のアクションに移行できます

### ■Path

`app/controllers/sessions_controller.rb`

`app/views/sessions/new.html.erb`

`app/assets/javascripts/sessions.js`

### ■Tasks

- [ ]  `app/controllers/sessions_controller.rb`にて、ログイン成功時に渡すフラッシュメッセージにリンク情報を追加
- [ ]  `app/views/sessions/new.html.erb`にJavaScriptファイルを読み込むためのコードを追加
- [ ]  `app/views/layouts/application.html.erb`にフラッシュメッセージを表示するための領域を追加
- [ ]  `app/assets/javascripts/sessions.js`を修正し、ポップアップにリンクを表示できるようにする。
    - [ ]  各リンクのURLを設定
    - [ ]  ポップアップ内にリンクボタンを配置
    - [ ]  リンクのスタイルを調整

### ■Goals

ログイン成功時に表示されるポップアップメッセージ内に、トップページ、プレイヤー切り替えページ、および問題ページへのリンクが表示され、ユーザーが次のアクションにスムーズに移行できること
