### ISSUE TITLE
マイページ編集画面のユーザー編集フォームを作成（view)

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#90]
### ■Summary

ユーザーが自身の情報を編集できるマイページの編集画面を作成する

### ■Path

`_edit_user.html.erb`

### ■Tasks

- [ ]  `_edit_user.html.erb`を作成
- [ ]  `form_with`ヘルパーを使用して以下のフォームを追加
    - [ ]  username：ユーザーネーム
    - [ ]  profile_image：プロフィール画像アップロードフォーム
- [ ]  各フォームに対応する適切なフィールドとラベルを追加

### ■Goals

ユーザーが自身のユーザーネームとプロフィール画像を編集するフォームが表示される
