### ISSUE TITLE
マイページ編集画面のプレイヤー作成フォームを作成（view)

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#91]
### ■Summary

ユーザーが新しいプレイヤーを作成できるマイページの編集画面を作成する

### ■Path

`_new_player.html.erb`

### ■Tasks

- [ ]  `app/views/mypage/_new_player.html.erb`を作成
- [ ]  `form_with`ヘルパーを使用して以下のフォームを追加
    - [ ]  プレイヤーの新規作成フォーム
        - [ ]  name：名前
        - [ ]  birthday：誕生日
        - [ ]  gender：性別（選択式）
        - [ ]  profile_image：プロフィール画像
- [ ]  各フォームに対応する適切なフィールドとラベルを追加

### ■Goals

ユーザーが新しいプレイヤーを作成するフォームが表示される
