### ISSUE TITLE
マイページ編集画面のプレイヤー編集・削除フォームを作成（view)

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#92]
### ■Summary

ユーザーが既存のプレイヤーを編集・削除できるマイページの編集画面を作成する

### ■Path

`_edit_player.html.erb`

### ■Tasks

- [ ]  `app/views/mypage/_edit_player.html.erb`を作成
- [ ]  `form_with`ヘルパーを使用して以下のフォームを追加
    - [ ]  プレイヤーの編集フォーム
        - [ ]  name：名前を編集するためのテキストフィールド
        - [ ]  birthday：誕生日を編集するための入力フィールド
        - [ ]  gender：性別を編集するための選択肢（ドロップダウン）
        - [ ]  profile_image：プロフィール画像アップロードフォーム
        - [ ]  既存のプレイヤー削除ボタン（各プレイヤーごとに）
    - [ ]  フォームの各フィールドに適切なラベルとプレースホルダーを追加し、ユーザーにわかりやすくする

### ■Goals

- ユーザーが既存のプレイヤーを編集するフォームが表示される
- ユーザーが既存のプレイヤーを削除するフォームが表示される
