### ISSUE TITLE
JavaScriptによる画像アップロードの選択肢表示

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#95]
### ■Summary

ユーザーとプレイヤーのプロフィール画像をクリックすると、「写真を選ぶ」「未設定状態に戻す」オプションが表示され、画像をアップロードまたは削除するが、右上の完了ボタンをクリックするまでデータの更新は行わない

### ■Path

`app/assets/javascripts/mypage.js`

### ■Tasks

- [ ]  **JavaScriptファイルの作成**
    - [ ]  `app/assets/javascripts/mypage.js`を作成
    - [ ]  プロフィール画像をクリックすると、画像選択オプションが表示されるようにするJavaScriptを追加
        - [ ]  写真を選ぶ
        - [ ]  未設定状態に戻す
    - [ ]  「写真を選ぶ」を選択した場合に、画像ファイル選択ダイアログを表示するJavaScriptを追加
    - [ ]  「未設定状態に戻す」を選択した場合に、画像を削除するリクエストを送信するJavaScriptを追加
    - [ ]  変更された画像情報をhiddenフィールドに保存するJavaScriptを追加
- [ ]  **画像のアップロード処理**
    - [ ]  画像ファイルを選択した際に、フォームに追加された画像をプレビュー表示するJavaScriptを追加
    - [ ]  プレビュー表示された画像の情報をhiddenフィールドに保存するJavaScriptを追加
- [ ]  **画像の削除処理**
    - [ ]  画像の削除ボタンをクリックした際に、確認ダイアログを表示するJavaScriptを追加
    - [ ]  確認ダイアログで「はい」を選択した場合に、画像を削除するリクエストを送信するJavaScriptを追加
    - [ ]  画像の削除が成功した場合に、プロフィール画像をデフォルトの画像に変更し、hiddenフィールドにその情報を保存するJavaScriptを追加
- [ ]  右上の完了ボタンをクリックした際に、すべてのhiddenフィールドの情報を含むフォームを送信する処理を追加

### ■Goals

- プロフィール画像をクリックすると、「写真を選ぶ」「未設定状態に戻す」オプションが表示されること
- 画像をアップロードおよび削除できるが、右上の完了ボタンをクリックするまでデータは更新されないこと
- 変更された画像情報がhiddenフィールドに保存され、フォーム送信時に反映されること
