### ISSUE TITLE
コントローラーの更新とルーティングの設定

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#96]
### ■Summary

ユーザーとプレイヤーのプロフィール画像の保存と削除を行うためのコントローラーを更新し、ルーティングを設定します

### ■Path

`app/controllers/users_controller.rb`

`app/controllers/players_controller.rb`

`config/routes.rb`

### ■Tasks

- [ ]  `app/controllers/users_controller.rb`を作成し、プロフィール画像の保存・削除機能を実装
    - [ ]  new, create, destroyアクションを追加
- [ ]  `app/controllers/players_controller.rb`を作成し、プロフィール画像の保存・削除機能を実装
    - [ ]  new, create, destroyアクションを追加
- [ ]  ルーティングを設定し、上記のアクションに対応するルートを追加

### ■Goals

ユーザーとプレイヤーのプロフィール画像の保存と削除が正しく行われること
