### ISSUE TITLE
画像のバリデーションと保存場所の設定

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#97]
### ■Summary

プロフィール画像のアップロード時にファイルサイズや形式のバリデーションを追加し、CarrierWaveの設定ファイルを作成して環境ごとの保存場所を設定します

### ■Path

`app/uploaders/profile_image_uploader.rb`

`config/initializers/carrierwave.rb`

### ■Tasks

- [ ]  画像のバリデーションを追加
    - [ ]  `app/uploaders/profile_image_uploader.rb`にファイルサイズや形式のバリデーションを追加
        - [ ]  `size`メソッドを使って最大ファイルサイズを設定
        - [ ]  `extension_whitelist`メソッドを使って許可するファイル形式を設定
- [ ]  CarrierWaveの設定ファイルを作成
    - [ ]  `config/initializers/carrierwave.rb`を作成し、環境ごとの保存場所を設定。
        - [ ]  開発環境ではローカルに保存
        - [ ]  本番環境ではS3に保存

### ■Goals

- プロフィール画像アップロード時にファイルサイズや形式のバリデーションが適用されること
- 開発環境ではローカルに、そして本番環境ではS3に画像が保存されること
