### ISSUE TITLE
プレイヤーの新規作成入力フォームを追加する機能

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#98]
### ■Summary

「＋子どもプロフィールを追加する」ボタンをクリックすると、新しいプレイヤーの入力フォームが表示されるようにします

### ■Path

`app/views/mypage/edit.html.erb`

`app/assets/javascripts/mypage.js`

### ■Tasks

- [ ]  `app/views/mypage/edit.html.erb`に「+ 子どもプロフィールを追加する」ボタンを設置する
- [ ]  プレイヤーの入力フォームは`app/views/mypage/_new_player.html.erb`を使用してrender
- [ ]  `app/assets/javascripts/mypage.js`を作成し、ボタンをクリックしたときにフォームを表示する機能を実装
    - [ ]  「+ 子どもプロフィールを追加する」ボタンのクリックイベントを監視し、クリックされたら部分テンプレート`_new_player.html.erb`を動的に挿入する
    - [ ]  フォームが表示されたときに適切に動作するかを確認し、必要に応じてデバッグする
- [ ]  `app/views/layouts/application.html.erb` にJavaScriptファイルを読み込むコードを追加

### ■Goals

- 「+ 子どもプロフィールを追加する」ボタンをクリックすると、プレイヤーの入力フォームが表示されること。
- 新しいプレイヤーの入力フォームが正常に表示され、ユーザーが入力できること
