### ISSUE TITLE
プレイヤー作成・編集・削除時のコントローラの実装

### ISSUE THREAD

**Issue by renasugiyama** [renasugiyama/working_vehicles_english#99]
### ■Summary

プレイヤーの作成、編集、削除を行う際に、変更内容を一時的に保存し、マイページ編集画面の右上の完了ボタンをクリックするまでサーバーに送信されないようにする

### ■Path

`app/controllers/players_controller.rb`

`app/views/mypage/_new_player.html.erb`

`app/views/mypage/_edit_player.html.erb`

`app/assets/javascripts/mypage.js`

`app/models/player.rb`

### ■Tasks

1. フロントエンドの実装
- [ ]  `app/assets/javascripts/mypage.js`ファイルに以下の機能を追加
    - [ ]  プレイヤー削除ボタンをクリックしたときに確認ダイアログを表示し、削除情報をhiddenフィールドに保存する
    - [ ]  新規プレイヤー作成フォームのデータをhiddenフィールドに保存する
    - [ ]  プレイヤー編集フォームのデータをhiddenフィールドに保存する
1. コントローラーの実装
- [ ]  `app/controllers/players_controller.rb`の修正
    - [ ]  `new`アクション：新規プレイヤーフォームの表示
    - [ ]  `create`アクション：新しいプレイヤーの作成（フォームからのデータ受け取り、保存処理）
    - [ ]  `edit`アクション：既存プレイヤーフォームの表示
    - [ ]  `update`アクション：既存プレイヤーの編集（フォームからのデータ受け取り、更新処理）
    - [ ]  `destroy`アクション：プレイヤーの削除（確認ダイアログからのデータ受け取り、削除処理）
1. ルーティングの設定
- [ ]  `config/routes.rb`に次のルーティングを追加
    - [ ]  `resources :players, only: [:new, :create, :edit, :update, :destroy]`

4.モデル

- [ ]  Playerモデルにバリデーションを追加する
    - [ ]  名前: `presence: true`, `length: { maximum: 50 }`
    - [ ]  誕生日: `presence: true`
    - [ ]  性別: `inclusion: { in: %w[male female] }`
    - [ ]  プロフィール画像: `content_type: { in: %w[image/jpeg image/gif image/png]`
- [ ]  バリデーションエラーメッセージを表示する

### ■Goals

- プレイヤーの作成、編集、削除を行う際に、変更内容が即時サーバーに送信されない
- マイページ編集画面の完了ボタンをクリックすることで、一括して変更内容がサーバーに送信される
- 変更成功時および失敗時のフラッシュメッセージが適切に表示される
